### ISSUE TITLE
auto-host.h not found

### ISSUE THREAD

**Issue by abarbaro** [davidmalcolm/gcc-python-plugin#113]
Hi,
I'm trying to compile the project on my Linux machine running gcc 6.3.0 and with python and six installed but I had the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/gcc/x86_64-linux-gnu/6/plugin/include/auto-host.h'
```

Any idea on how to fix it please?

Thanks

**Comment by davidmalcolm** [comment]
Looks like output from generate-config-h.py

Is there more output than that?  Can you post the full log please?

**Comment by abarbaro** [comment]
Hi @davidmalcolm ,
sure that's the full output:

```
➜  gcc-python-plugin git:(master) make
Makefile:193: warning: overriding recipe for target 'autogenerated-casts.c'
Makefile:190: warning: ignoring old recipe for target 'autogenerated-casts.c'
python generate-config-h.py -o autogenerated-config.h --gcc="cc" --plugindir="/usr/lib/gcc/x86_64-linux-gnu/6/plugin"
Checking whether cc was built with C or C++... Traceback (most recent call last):
  File "generate-config-h.py", line 125, in <module>
    ch.main()
  File "generate-config-h.py", line 44, in main
    self.test_whether_built_with_cplusplus()
  File "generate-config-h.py", line 93, in test_whether_built_with_cplusplus
    with open(auto_host_h, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/gcc/x86_64-linux-gnu/6/plugin/include/auto-host.h'
Makefile:177: recipe for target 'autogenerated-config.h' failed
make: *** [autogenerated-config.h] Error 1
```
So the plugin dir exist but the include dir does not so obviously also the .h does not.

Any idea?

Thanks

**Comment by davidmalcolm** [comment]
Aha: looks like the plugin includes are missing.

Thanks.

Is the gcc 6 installed via a package manager (e.g. apt/.deb or rpm/yum/dnf)?  If so, maybe there's another package you need to install.  On Fedora/RHEL I believe it's "gcc-plugin-devel".

We should probably provide a better error message for this.

**Comment by abarbaro** [comment]
@davidmalcolm , how did I miss that? :)

I had to install ```gcc-6-plugin-dev```, my suggestion is to update the README file on github.

Thanks

**Comment by davidmalcolm** [comment]
That one looks like a dup of issue #112.

**Comment by dvarrazzo** [comment]
FYI, on Ubuntu "auto-host.h not found" is solved by installing the gcc-X-plugin-dev package for the right gcc version.
