### ISSUE TITLE
unhandled python exception in impl_PyList_Append (AttributeError: 'UnknownValue' object has no attribute 'region')

### ISSUE THREAD

**Issue by davidmalcolm** [davidmalcolm/gcc-python-plugin#59]
I got this unhandled Python exception when building gdb with the plugin.
{{{
../../archer/gdb/python/py-breakpoint.c: In function ‘build_bp_list’:
../../archer/gdb/python/py-breakpoint.c:707:11: error: Unhandled Python exception raised calling 'execute' method
Traceback (most recent call last):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/__init__.py", line 64, in execute
    self._check_refcounts(fun)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/__init__.py", line 68, in _check_refcounts
    self.show_possible_null_derefs)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/refcounts.py", line 2838, in check_refcounts
    limits=limits)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2716, in iter_traces
    depth + 1):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2716, in iter_traces
    depth + 1):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2716, in iter_traces
    depth + 1):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2716, in iter_traces
    depth + 1):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2716, in iter_traces
    depth + 1):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2716, in iter_traces
    depth + 1):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2716, in iter_traces
    depth + 1):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2680, in iter_traces
    transitions = curstate.get_transitions()
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 1828, in get_transitions
    return self._get_transitions_for_stmt(stmt)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 1844, in _get_transitions_for_stmt
    return self._get_transitions_for_GimpleCall(stmt)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 1995, in _get_transitions_for_GimpleCall
    return meth(stmt, *args)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/refcounts.py", line 1517, in impl_PyList_Append
    ob_item_region = self.state.make_field_region(v_op.region, 'ob_item')
AttributeError: 'UnknownValue' object has no attribute 'region'
}}}

**Comment by davidmalcolm** [comment]
_Imported from trac issue 19.  Created by tromey on 2012-01-04T16:47:17, last modified: 2012-01-06T16:23:38_

**Comment by davidmalcolm** [comment]
_Trac comment by dmalcolm on 2012-01-06 16:23:38:_

Fixed in a9bb2d74e96d6edef900ed4fe47c23b5bdd98d09
