### ISSUE TITLE
unhandled python exception in check_refcounts (AttributeError: 'ConcreteValue' object has no attribute 'region')

### ISSUE THREAD

**Issue by davidmalcolm** [davidmalcolm/gcc-python-plugin#60]
I got this unhandled Python exception when building gdb with the checker:
{{{
../../archer/gdb/python/py-breakpoint.c: In function ‘bppy_init’:
../../archer/gdb/python/py-breakpoint.c:631:5: error: Unhandled Python exception raised calling 'execute' method
Traceback (most recent call last):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/__init__.py", line 64, in execute
    self._check_refcounts(fun)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/__init__.py", line 68, in _check_refcounts
    self.show_possible_null_derefs)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/refcounts.py", line 3017, in check_refcounts
    if isinstance(return_value.region, RegionForGlobal):
AttributeError: 'ConcreteValue' object has no attribute 'region'
}}}

**Comment by davidmalcolm** [comment]
_Imported from trac issue 20.  Created by tromey on 2012-01-04T16:47:52, last modified: 2012-01-05T17:34:52_

**Comment by davidmalcolm** [comment]
_Trac comment by dmalcolm on 2012-01-05 17:34:52:_

Fixed in 415731890507cb19e43f41008519429cebc95dfa
