### ISSUE TITLE
NotImplementedError from checker (Don't know how to cope with exprcode: <type 'gcc.RealCst'>)

### ISSUE THREAD

**Issue by davidmalcolm** [davidmalcolm/gcc-python-plugin#63]
I saw this NotImplementedError when running the checker on gdb.
{{{
../../archer/gdb/python/py-value.c: In function ‘valpy_float’:
../../archer/gdb/python/py-value.c:1098:10: error: Unhandled Python exception raised calling 'execute' method
Traceback (most recent call last):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/__init__.py", line 64, in execute
    self._check_refcounts(fun)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/__init__.py", line 68, in _check_refcounts
    self.show_possible_null_derefs)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/refcounts.py", line 2838, in check_refcounts
    limits=limits)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2716, in iter_traces
    depth + 1):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2716, in iter_traces
    depth + 1):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2716, in iter_traces
    depth + 1):
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2680, in iter_traces
    transitions = curstate.get_transitions()
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 1828, in get_transitions
    return self._get_transitions_for_stmt(stmt)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 1855, in _get_transitions_for_stmt
    return self._get_transitions_for_GimpleAssign(stmt)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2308, in _get_transitions_for_GimpleAssign
    value = self.eval_rhs(stmt)
  File "/home/tromey/Space/Trunk/gcc-python-plugin/libcpychecker/absinterp.py", line 2300, in eval_rhs
    % (stmt.exprcode, stmt.exprcode, stmt.loc))
NotImplementedError: Don't know how to cope with exprcode: <type 'gcc.RealCst'> (<type 'gcc.RealCst'>) at ../../archer/gdb/python/py-value.c:1098
}}}

**Comment by davidmalcolm** [comment]
_Imported from trac issue 23.  Created by tromey on 2012-01-05T09:21:41, last modified: 2012-01-05T18:30:09_

**Comment by davidmalcolm** [comment]
_Trac comment by dmalcolm on 2012-01-05 18:30:09:_

Fixed in e953afafe6f13f8e2c07265073024f793b7a5083
