### ISSUE TITLE
python2.6 incompatible

### ISSUE THREAD

**Issue by davidmalcolm** [davidmalcolm/gcc-python-plugin#96]
Crash when using python2.6

{{{
$ make
Makefile:189: warning: overriding commands for target `autogenerated-casts.c'
Makefile:186: warning: ignoring old commands for target `autogenerated-casts.c'
python generate-config-h.py -o autogenerated-config.h --gcc="cc" --plugindir="plugin"
Traceback (most recent call last):
  File "generate-config-h.py", line 21, in <module>
    from configbuilder import ConfigBuilder, CheckFor
  File "/nail/home/buck/trees/theirs/gcc-python-plugin/configbuilder.py", line 20, in <module>
    from subprocess import Popen, PIPE, check_output
ImportError: cannot import name check_output
make: *** [autogenerated-config.h] Error 1
}}}

This function was added in 2.7. It's pretty easy to shim out, but should at minimum update the doc:

https://gcc-python-plugin.readthedocs.org/en/latest/basics.html

**Comment by davidmalcolm** [comment]
_Imported from trac issue 56.  Created by bukzor on 2014-03-06T18:42:15, last modified: 2014-03-06T18:42:15_
